### ISSUE TITLE
Please update the package dependencies

### ISSUE THREAD

**Issue by sagar1garg** [iamvivekkaushik/DatePickerTimelineFlutter#95]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iamvivekkaushik** [comment]
Hi @sagar1garg, thanks for the nudge — this is sorted in v1.3.0, released this week.

The package now declares:
```
environment:
  sdk: '>=3.5.0 <4.0.0'   # Flutter 3.24+
dependencies:
  intl: '>=0.19.0 <0.21.0'
The wide intl range means it resolves cleanly alongside other packages whether your app is on intl 0.19 or 0.20. A flutter pub upgrade date_picker_timeline should do it.
```
Closing this as done — if you still hit a version-solving conflict on 1.3.0, please reopen with the resolver output and I'll take a look.
